#AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"fix_annotations_format": "00_core.ipynb",
         "dataset_stats": "00_core.ipynb",
         "ents_by_label": "00_core.ipynb",
         "get_label_disparities": "00_core.ipynb"}

modules = ["core.py"]

git_url = "https://github.com/kabirkhan/spacy_data_debug/tree/master/"

def custom_doc_links(name): return None